# pyproject.toml
[project]
name = "Simple-video-effects"  # Unique and immutable node identifier.
description = "Nodes for Video effects. Zoom In/Out - new features soon."
version = "1.0.0"  # Semantic versioning
dependencies = []  # Populated from requirements.txt if present.

[project.urls]
Repository = "https://github.com/scofano/ComfyUI-Simple-video-effects"

[tool.comfy]
PublisherId = "dansco"
DisplayName = "Simple Video Effects"